name: backfill-all-rounds

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  backfill:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20 }
      - name: Run backfill
        env:
          SLEEP_MS: "300"   # 호출 간 짧은 지연(권장)
        run: |
          mkdir -p public/rounds
          node scripts/backfill-all.mjs
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add public/index.json public/history.json public/rounds/*.json
            git commit -m "chore: backfill rounds"
            git push
          else
            echo "No changes."
          fi
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with: { path: ./public }

  deploy:
    needs: backfill
    runs-on: ubuntu-latest
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/deploy-pages@v4
